name: Deploy to Production

on:
  push:
    branches:
      - main
      
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Install dependencies
      run: dotnet restore EasyButton/easy-button.csproj
      
    - name: Build
      run: dotnet build EasyButton/easy-button.csproj
      
    - name: Test
      run: dotnet test EasyButton.Tests/EasyButton.Tests.csproj
      
  deploy:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to cloud.gov
        uses: cloud-gov/cg-cli-tools@main
        with: 
          cf_api: https://api.fr.cloud.gov
          cf_username: ${{ secrets.CG_USERNAME }}
          cf_password: ${{ secrets.CG_PASSWORD }}
          cf_org: ${{ secrets.CG_ORG }}
          cf_space: ${{ secrets.CG_SPACE }}
          cf_command: push dotnet-core-cd --strategy rolling

